package by.it_academy.belaya.enums;

public enum Countries {
    AFGHANISTAN("AFGHANISTAN", "fa_AF"),
    ALBANIA("ALBANIA", "sq_AL"),
    ALGERIA("ALGERIA", "ar_DZ"),
    ANDORRA("ANDORRA", "ca_AD"),
    ANGOLA("ANGOLA", "pt_AO"),
    ANTIGUA_AND_BARBUDA("ANTIGUA AND BARBUDA", "en_AG"),
    ARGENTINA("ARGENTINA", "es_AR"),
    ARMENIA("ARMENIA", "hy_AM"),
    AUSTRALIA("AUSTRALIA", "en_AU"),
    AUSTRIA("AUSTRIA", "de_AT"),
    AZERBAIJAN("AZERBAIJAN", "az_AZ"),
    BAHAMAS("BAHAMAS", "en_BS"),
    BAHRAIN("BAHRAIN", "ar_BH"),
    BANGLADESH("BANGLADESH", "bn_BD"),
    BARBADOS("BARBADOS", "en_BB"),
    BELARUS("BELARUS", "be_BY"),
    BELGIUM("BELGIUM", "nl_BE"),
    BELIZE("BELIZE", "en_BZ"),
    BENIN("BENIN", "fr_BJ"),
    BHUTAN("BHUTAN", "dz_BT"),
    BOLIVIA("BOLIVIA", "es_BO"),
    BOSNIA_AND_HERZEGOVINA("BOSNIA AND HERZEGOVINA", "bs_BA"),
    BOTSWANA("BOTSWANA", "en_BW"),
    BRAZIL("BRAZIL", "pt_BR"),
    BRUNEI("BRUNEI", "ms_BN"),
    BULGARIA("BULGARIA", "bg_BG"),
    BURKINA_FASO("BURKINA FASO", "fr_BF"),
    BURUNDI("BURUNDI", "fr_BI"),
    CABO_VERDE("CABO VERDE", "pt_CV"),
    CAMBODIA("CAMBODIA", "km_KH"),
    CAMEROON("CAMEROON", "fr_CM"),
    CANADA("CANADA", "en_CA"),
    CENTRAL_AFRICAN_REPUBLIC("CENTRAL AFRICAN REPUBLIC", "fr_CF"),
    CHAD("CHAD", "fr_TD"),
    CHILE("CHILE", "es_CL"),
    CHINA("CHINA", "zh_CN"),
    COLOMBIA("COLOMBIA", "es_CO"),
    COMOROS("COMOROS", "ar_KM"),
    COSTA_RICA("COSTA RICA", "es_CR"),
    CROATIA("CROATIA", "hr_HR"),
    CUBA("CUBA", "es_CU"),
    CYPRUS("CYPRUS", "el_CY"),
    CZECH_REPUBLIC("CZECH REPUBLIC", "cs_CZ"),
    DENMARK("DENMARK", "da_DK"),
    DJIBOUTI("DJIBOUTI", "fr_DJ"),
    DOMINICA("DOMINICA", "en_DM"),
    DOMINICAN_REPUBLIC("DOMINICAN REPUBLIC", "es_DO"),
    EAST_TIMOR("EAST TIMOR", "pt_TL"),
    ECUADOR("ECUADOR", "es_EC"),
    EGYPT("EGYPT", "ar_EG"),
    EL_SALVADOR("EL SALVADOR", "es_SV"),
    EQUATORIAL_GUINEA("EQUATORIAL GUINEA", "es_GQ"),
    ERITREA("ERITREA", "ti_ER"),
    ESTONIA("ESTONIA", "et_EE"),
    ESWATINI("ESWATINI", "en_SZ"),
    ETHIOPIA("ETHIOPIA", "am_ET"),
    FIJI("FIJI", "en_FJ"),
    FINLAND("FINLAND", "fi_FI"),
    FRANCE("FRANCE", "fr_FR"),
    GABON("GABON", "fr_GA"),
    GAMBIA("GAMBIA", "en_GM"),
    GEORGIA("GEORGIA", "ka_GE"),
    GERMANY("GERMANY", "de_DE"),
    GHANA("GHANA", "en_GH"),
    GREECE("GREECE", "el_GR"),
    GRENADA("GRENADA", "en_GD"),
    GUATEMALA("GUATEMALA", "es_GT"),
    GUINEA("GUINEA", "fr_GN"),
    GUINEA_BISSAU("GUINEA BISSAU", "pt_GW"),
    GUYANA("GUYANA", "en_GY"),
    HAITI("HAITI", "ht_HT"),
    HONDURAS("HONDURAS", "es_HN"),
    HONG_KONG("HONG KONG", "zh_HK"),
    HUNGARY("HUNGARY", "hu_HU"),
    ICELAND("ICELAND", "is_IS"),
    INDIA("INDIA", "hi_IN"),
    INDONESIA("INDONESIA", "id_ID"),
    IRAN("IRAN", "fa_IR"),
    IRAQ("IRAQ", "ar_IQ"),
    IRELAND("IRELAND", "en_IE"),
    ISRAEL("ISRAEL", "he_IL"),
    ITALY("ITALY", "it_IT"),
    JAMAICA("JAMAICA", "en_JM"),
    JAPAN("JAPAN", "ja_JP"),
    JORDAN("JORDAN", "ar_JO"),
    KAZAKHSTAN("KAZAKHSTAN", "kk_KZ"),
    KENYA("KENYA", "en_KE"),
    KIRIBATI("KIRIBATI", "en_KI"),
    KOSOVO("KOSOVO", "sq_KV"),
    KUWAIT("KUWAIT", "ar_KW"),
    KYRGYZSTAN("KYRGYZSTAN", "ky_KG"),
    LAOS("LAOS", "lo_LA"),
    LATVIA("LATVIA", "lv_LV"),
    LEBANON("LEBANON", "ar_LB"),
    LESOTHO("LESOTHO", "st_LS"),
    LIBERIA("LIBERIA", "en_LR"),
    LIBYA("LIBYA", "ar_LY"),
    LIECHTENSTEIN("LIECHTENSTEIN", "de_LI"),
    LITHUANIA("LITHUANIA", "lt_LT"),
    LUXEMBOURG("LUXEMBOURG", "lb_LU"),
    MADAGASCAR("MADAGASCAR", "mg_MG"),
    MALAWI("MALAWI", "en_MW"),
    MALAYSIA("MALAYSIA", "ms_MY"),
    MALDIVES("MALDIVES", "dv_MV"),
    MALI("MALI", "fr_ML"),
    MALTA("MALTA", "mt_MT"),
    MARSHALL_ISLANDS("MARSHALL ISLANDS", "en_MH"),
    MAURITANIA("MAURITANIA", "ar_MR"),
    MAURITIUS("MAURITIUS", "en_MU"),
    MEXICO("MEXICO", "es_MX"),
    MICRONESIA("MICRONESIA", "en_FM"),
    MOLDOVA("MOLDOVA", "ro_MD"),
    MONACO("MONACO", "fr_MC"),
    MONGOLIA("MONGOLIA", "mn_MN"),
    MONTENEGRO("MONTENEGRO", "sr_ME"),
    MOROCCO("MOROCCO", "ar_MA"),
    MOZAMBIQUE("MOZAMBIQUE", "pt_MZ"),
    MYANMAR("MYANMAR", "my_MM"),
    NAMIBIA("NAMIBIA", "en_NA"),
    NAURU("NAURU", "en_NR"),
    NEPAL("NEPAL", "ne_NP"),
    NETHERLANDS("NETHERLANDS", "nl_NL"),
    NEW_ZEALAND("NEW ZEALAND", "en_NZ"),
    NICARAGUA("NICARAGUA", "es_NI"),
    NIGER("NIGER", "fr_NE"),
    NIGERIA("NIGERIA", "en_NG"),
    NORTH_KOREA("NORTH KOREA", "ko_KP"),
    NORWAY("NORWAY", "no_NO"),
    OMAN("OMAN", "ar_OM"),
    PAKISTAN("PAKISTAN", "ur_PK"),
    PALAU("PALAU", "en_PW"),
    PANAMA("PANAMA", "es_PA"),
    PAPUA_NEW_GUINEA("PAPUA NEW GUINEA", "en_PG"),
    PARAGUAY("PARAGUAY", "es_PY"),
    PERU("PERU", "es_PE"),
    PHILIPPINES("PHILIPPINES", "fil_PH"),
    POLAND("POLAND", "pl_PL"),
    PORTUGAL("PORTUGAL", "pt_PT"),
    QATAR("QATAR", "ar_QA"),
    ROMANIA("ROMANIA", "ro_RO"),
    RUSSIA("RUSSIA", "ru_RU"),
    RWANDA("RWANDA", "rw_RW"),
    SAINT_KITTS_AND_NEVIS("SAINT KITTS AND NEVIS", "en_KN"),
    SAINT_LUCIA("SAINT LUCIA", "en_LC"),
    SAINT_VINCENT_AND_THE_GRENADINES("SAINT VINCENT AND THE GRENADINES", "en_VC"),
    SAMOA("SAMOA", "sm_WS"),
    SAN_MARINO("SAN MARINO", "it_SM"),
    SAO_TOME_AND_PRINCIPE("SAO TOME AND PRINCIPE", "pt_ST"),
    SAUDI_ARABIA("SAUDI ARABIA", "ar_SA"),
    SENEGAL("SENEGAL", "fr_SN"),
    SERBIA("SERBIA", "sr_RS"),
    SEYCHELLES("SEYCHELLES", "en_SC"),
    SIERRA_LEONE("SIERRA LEONE", "en_SL"),
    SINGAPORE("SINGAPORE", "en_SG"),
    SINT_MAARTEN("SINT MAARTEN", "nl_SX"),
    SLOVAKIA("SLOVAKIA", "sk_SK"),
    SLOVENIA("SLOVENIA", "sl_SI"),
    SOLOMON_ISLANDS("SOLOMON ISLANDS", "en_SB"),
    SOMALIA("SOMALIA", "so_SO"),
    SOUTH_AFRICA("SOUTH AFRICA", "en_ZA"),
    SOUTH_KOREA("SOUTH KOREA", "ko_KR"),
    SRI_LANKA("SRI LANKA", "si_LK"),
    SUDAN("SUDAN", "ar_SD"),
    SURINAME("SURINAME", "nl_SR"),
    SWEDEN("SWEDEN", "sv_SE"),
    SWITZERLAND("SWITZERLAND", "de_CH"),
    SYRIA("SYRIA", "ar_SY"),
    TAIWAN("TAIWAN", "zh_TW"),
    TAJIKISTAN("TAJIKISTAN", "tg_TJ"),
    TANZANIA("TANZANIA", "sw_TZ"),
    THAILAND("THAILAND", "th_TH"),
    TOGO("TOGO", "fr_TG"),
    TONGA("TONGA", "en_TO"),
    TRINIDAD_AND_TOBAGO("TRINIDAD AND TOBAGO", "en_TT"),
    TUNISIA("TUNISIA", "ar_TN"),
    TURKMENISTAN("TURKMENISTAN", "tk_TM"),
    TUVALU("TUVALU", "en_TV"),
    UGANDA("UGANDA", "en_UG"),
    UKRAINE("UKRAINE", "uk_UA"),
    UNITED_ARAB_EMIRATES("UNITED ARAB EMIRATES", "ar_AE"),
    UNITED_KINGDOM("UNITED KINGDOM", "en_GB"),
    UNITED_STATES("UNITED STATES", "en_US"),
    URUGUAY("URUGUAY", "es_UY"),
    UZBEKISTAN("UZBEKISTAN", "uz_UZ"),
    VANUATU("VANUATU", "bi_VU"),
    VATICAN_CITY("VATICAN CITY", "la_VA"),
    VENEZUELA("VENEZUELA", "es_VE"),
    VIETNAM("VIETNAM", "vi_VN"),
    YEMEN("YEMEN", "ar_YE"),
    ZAMBIA("ZAMBIA", "en_ZM"),
    ZIMBABWE("ZIMBABWE", "en_ZW");

    private final String countryName;
    private final String locale;

    Countries(String countryName, String locale) {
        this.countryName = countryName;
        this.locale = locale;
    }

    public String getCountryName() {
        return countryName;
    }

    public String getLocale() {
        return locale;
    }
}
